name: Test
on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run tests
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: swift test --enable-code-coverage --disable-automatic-resolution
